### ISSUE TITLE
[Feature Request] Dropbox like right-click action

### ISSUE THREAD

**Issue by vgezer** [schiesbn/shareLinkCreator#6]
In Windows native client of Dropbox, one can simply right-click on a file in Dropbox directory and choose get public link.

Can it be possible to do this on ownCloud with this software?

**Comment by 5ulo** [comment]
Nothing needs to be added. I tested it right now: upload single file, upload multiple files, upload single folder and upload multiple folders. Each upload returns an url link and all was correct. I just added exec link in action config (nemo filemanager):
Exec=/foo/bar/shareLinkCreator/shareLinkCreator %F

**Comment by schiesbn** [comment]
> In Windows native client of Dropbox, one can simply right-click on a file in Dropbox directory and choose get public link.

This should also work with the latest ownCloud desktop client for windows, macox and the nautilus file manager on GNU/Linux.

This script has a slightly different scope where you want to just upload a new file and get a link for it. E.g. to show a screenshot on a mailing list, quickly share a file with a friend which is not yet stored on the ownCloud server etc.
